Remove unnecessary db query
sandboxnu/office-hours pull request #231
Opened 2020-09-01 17:51 UTC by willstenzel

Looks like we don't need this query. 

Getting questions for the queue comes from the `/queues/:queue_id/questions` endpoint

2020-09-02 21:50 UTC, NEUDitao approved these changes

2020-09-02 23:09 UTC, dajinchu requested changes
don't we need questions to be loaded for the `queueSize` property on `QueueModel`? 
https://github.com/sandboxnu/office-hours/blob/5f7268d6ee0f3d52eaadab9616c68a12e7d9ad52/packages/server/src/queue/queue.entity.ts#L81-L85

2020-09-03 02:54 UTC, willstenzel commented
> don't we need questions to be loaded for the `queueSize` property on `QueueModel`?
> https://github.com/sandboxnu/office-hours/blob/5f7268d6ee0f3d52eaadab9616c68a12e7d9ad52/packages/server/src/queue/queue.entity.ts#L81-L85


I think they are being eagerly loaded so it's not needed anymore. 
https://github.com/sandboxnu/office-hours/blob/849727aa3208747a584180e4bd8baba0dd05d2fd/packages/server/src/queue/queue.entity.ts#L42-L46

2020-09-03 11:21 UTC, liustanley approved these changes

2020-09-03 17:47 UTC, dajinchu approved these changes
Looks good. We may eventually need to un-eager load, but let's wait for real production perf stats to come in.

2020-09-03 21:39 UTC, merged