Limbo queue list
sandboxnu/office-hours pull request #249
Opened 2020-09-04 02:11 UTC by ofloody

2020-09-04 02:27 UTC, dajinchu approved these changes
Are we going to get rid of the Can't Find button? Otherwise students will see people cut in line in front of them right?

2020-09-04 03:26 UTC, liustanley requested changes
StudentQueueList looks good! For the TAQueueList, we don't need to separate `queuedQuestions` and `helpedQuestions`. I think TA's would be confused by a bunch of 0's at the top of the list, we can leave it all numbered like before.

Another thing is that we also need to adjust for the StudentBanner with the `useStudentQuestion` hook, as mentioned in #235

2020-09-07 22:19 UTC, liustanley approved these changes

2020-09-08 03:25 UTC, dajinchu approved these changes

2020-09-08 03:34 UTC, merged