changed all avatars to initials + colors
sandboxnu/office-hours pull request #290
Opened 2020-09-10 23:37 UTC by NEUDitao

they're beautiful I think

2020-09-11 02:47 UTC, willstenzel approved these changes
Good stuff!

Only thing is we might want to change the font on the large avatars (like the ones on the today page) to have the same text to size ratio as the profile. @liustanley might have an opinion on that

![image](https://user-images.githubusercontent.com/33739155/92847711-75414d00-f3b7-11ea-995b-8242c6763bbc.png)

2020-09-11 03:11 UTC, liustanley approved these changes
big brain looks good

i agree with will, just fix the text ratio on the today page and it's good to merge

2020-09-11 03:15 UTC, liustanley requested changes
wait nvm lol some changes that need to be made:
- [ ] Make standard text to avatar size ratio, consistency here is important
- [ ] Missed the avatar on `TAQueueCard`

2020-09-12 16:51 UTC, liustanley approved these changes

2020-09-12 17:42 UTC, dajinchu approved these changes

2020-09-12 17:42 UTC, dajinchu commented on packages/app/components/Queue/TA/TABanner.tsx
> +            </Avatar>
Very similar Avatar code appears 7 times. Is it possible to abstract?

2020-09-12 18:32 UTC, merged