[WIP] Fix recurring calendar events
sandboxnu/office-hours pull request #327
Opened 2020-09-17 04:36 UTC by liustanley

Note: adds Luxon right now, but probably won't need it after finding a solution
Note 2: need to alter node-ical declaration file, to add `rrule: any;` in `VEvent`, want to open a PR later for this

2020-09-22 04:01 UTC, NEUDitao approved these changes

2020-09-22 04:02 UTC, NEUDitao requested changes
fuck i accidentally approved while browosing

2020-09-22 04:04 UTC, willstenzel approved these changes
My sincere gratitude to those who worked on this 🙏 

This ticket would have drove me crazy

2020-09-23 17:51 UTC, NEUDitao approved these changes

2020-09-23 17:51 UTC, NEUDitao commented
bless up

2020-09-24 02:19 UTC, merged