Midnight checkout
sandboxnu/office-hours pull request #491
Opened 2020-12-21 06:20 UTC by dfarooq610

I am unsure if we still need this, but closes #367 (and hopefully this time with no bugs). @ofloody and I paired on this so long ago but we never actually sent in a PR. So this is it. 

My only concern: what do we do to prevent against the queue-clean service automatically checking out an actual office hours session at midnight? Like if there are office hours in some Russian Timezone that crosses the midnight boundary, how do we ensure that we don't screw over their office hours and all the students in it? 

Nevertheless, lets see how this goes

2020-12-22 06:12 UTC, willstenzel requested changes
Do we want to possibly record a check in/out event here? It might be hard to analyze the check in/out times if some TA's get cleaned out of the queue without an event. 

@NEUDitao any thoughts on this since you were working the check in/out events previously?

2020-12-22 06:56 UTC, NEUDitao commented
> Do we want to possibly record a check in/out event here? It might be hard to analyze the check in/out times if some TA's get cleaned out of the queue without an event. 
> 
> @NEUDitao any thoughts on this since you were working the check in/out events previously?

I think we 100% should. especially with data insights in mind, we'd want to show them in pairs

2020-12-22 17:01 UTC, NEUDitao commented
> > Do we want to possibly record a check in/out event here? It might be hard to analyze the check in/out times if some TA's get cleaned out of the queue without an event.
> > @NEUDitao any thoughts on this since you were working the check in/out events previously?
> 
> I think we 100% should. especially with data insights in mind, we'd want to show them in pairs

Though, something else to consider is we could also make a separate type of event for midnight checkouts...

2020-12-22 17:27 UTC, willstenzel commented
> > > Do we want to possibly record a check in/out event here? It might be hard to analyze the check in/out times if some TA's get cleaned out of the queue without an event.
> > > @NEUDitao any thoughts on this since you were working the check in/out events previously?
> > 
> > 
> > I think we 100% should. especially with data insights in mind, we'd want to show them in pairs
> 
> Though, something else to consider is we could also make a separate type of event for midnight checkouts...

Good idea. That way we when we go to find out how long TA's are spending in office hours we can compute it correctly by disregarding the check in/out times for the "cleaned TA's".

2020-12-26 23:32 UTC, dfarooq610 commented on packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
> +    });
Ahh ok its gone now

2020-12-28 19:50 UTC, willstenzel approved these changes
LGTM

2021-01-03 21:27 UTC, liustanley commented
- [ ] migration
- [ ] 3am EST checkout, doesn't checkout if overlaps with scheduled office hour

2021-02-01 19:08 UTC, willstenzel commented on packages/server/src/queue/queue-clean/queue-clean.service.spec.ts
> +    it.only('checkout all staff from all queues', async () => {
Remove `it.only`

2021-02-03 04:51 UTC, NEUDitao approved these changes

2021-02-04 03:39 UTC, merged