deploy script
sandboxnu/office-hours pull request #521
Opened 2021-01-12 15:24 UTC by dajinchu

2021-01-12 20:51 UTC, willstenzel approved these changes

2021-01-13 22:37 UTC, dajinchu commented
> this is great! how should we handle backfills when deploying though?

Just gonna have to ssh and run them. Usually we should write features in a way that not running the backfill just results in degraded service

2021-01-16 04:18 UTC, liustanley requested changes

2021-01-16 04:18 UTC, liustanley commented on infrastructure/prod/deploy.sh
> +chgrp -R officehours /var/www/source/.pm2
Oh wait this has to be `/var/www/.pm2`

2021-01-28 04:34 UTC, merged