anonymize student helping names to students
sandboxnu/office-hours pull request #624
Opened 2021-03-06 23:10 UTC by dfarooq610

# Description

Students can currently see the names of the other students that are being helped. I made it so that only TAs can see who other TAs are helping. 

**TA View**
![image](https://user-images.githubusercontent.com/59672089/110224090-a736f600-7ea6-11eb-8e37-fc4d782a2b70.png)

**Student Being Helped** 
![image](https://user-images.githubusercontent.com/59672089/110224144-1f052080-7ea7-11eb-9bd4-17d351c4cbe5.png)

**Other Student In Course**
![image](https://user-images.githubusercontent.com/59672089/110224124-faa94400-7ea6-11eb-830a-f9e4404bdd82.png)

Closes # (issue number) #604 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Visually on the Frontend through multiple user's views of the screen

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-07 06:03 UTC, willstenzel approved these changes

2021-03-07 19:19 UTC, NEUDitao commented
- Should be a `BlueSpan` for "a student"
- Also, the anonimization should happen in the _backend_ -- In `personalizeQuestions`, we need to also anonymize `questions.questinosGettingHelp` -- users can still see stuff in the API call

2021-03-07 19:19 UTC, NEUDitao requested changes
chekc the comment I made oops

2021-03-18 02:24 UTC, NEUDitao approved these changes

2021-03-18 02:24 UTC, NEUDitao commented on packages/server/src/queue/queue.service.ts
> +          Object.assign(newQ, question);
it seems like `newQ` isn't being used?

2021-03-19 00:18 UTC, merged