Queue Dropdown
sandboxnu/office-hours pull request #778
Opened 2021-11-27 23:01 UTC by VKong6019

# Description

Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Closes # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] This requires a run of `yarn install`

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-27 23:05 UTC, VKong6019 commented on packages/app/components/Nav/NavBarTabs.tsx
> +  courseId?: number;
i feel jank doing this; is there better way to do this lol

2021-12-06 00:41 UTC, ashdawngary requested changes
looks good, you should add cypress tests for testing the links (make sure they go to the correct queues, correct queue show up based on role, etc)

2021-12-17 07:44 UTC, VKong6019 commented
gonna add cool hip gif soon

2021-12-17 22:04 UTC, VKong6019 commented
![queue-tab](https://user-images.githubusercontent.com/23366632/146613174-0feeef5c-1f50-41b3-97e2-26edac3e69f6.gif)

Do we want to stay consistent with the list of queues shown between the CheckIn Modal and the Queue dropdown? I think the Queue dropdown just shows the queues that are open, whereas the modal shows all queues

2021-12-19 18:00 UTC, ashdawngary commented
weird bug:
![queue_doesnt_come_back](https://user-images.githubusercontent.com/11274412/146685568-c1b1f92a-713a-4482-a835-53318d3ee1fd.gif)

2021-12-20 15:44 UTC, IrisLiu-00 commented
> Do we want to stay consistent with the list of queues shown between the CheckIn Modal and the Queue dropdown? I think the Queue dropdown just shows the queues that are open, whereas the modal shows all queues

Hmmm good question. I think it should be fine if the dropdown only shows open queues - this does mean there's no way to navigate to a closed queue without checking into it, but I don't think you would ever have reason to do that anyways.

2021-12-20 18:01 UTC, IrisLiu-00 requested changes
Looking good, the only major request I have is to use the dropdown that's part of the antd Menu component

2021-12-21 03:55 UTC, VKong6019 commented on cypress.json
> +  "numTestsKeptInMemory": 1,
@ashdawngary you got it

2021-12-21 04:28 UTC, VKong6019 commented on packages/app/components/Nav/NavBarTabs.tsx
> +            <Dropdown
![image](https://user-images.githubusercontent.com/23366632/146871069-695ae34f-25eb-45b3-9603-cf5eeae9ed2f.png)
it's time for dark mode

2021-12-21 15:05 UTC, ashdawngary commented on cypress.json
> +  "numTestsKeptInMemory": 1,
github actions dies randomly on cypress causing it to hang and then time out -- just in case cypress is running out of memory and then hanging

2021-12-28 18:07 UTC, IrisLiu-00 approved these changes
LGTM! I just pushed a commit to center the submenu dropdown under the Queue tab, but you're good otherwise!

2021-12-30 03:00 UTC, merged