Automatically disable past semester courses
sandboxnu/office-hours pull request #907
Opened 2022-06-06 15:15 UTC by IrisLiu-00

# Description

Disable courses from past semesters when the Khoury login payload changes to a previously unseen semester. This eliminates the need for running a manual script; after this, running the app should be completely automatic. 

Generally speaking, each semester disables any other courses which are still enabled, except for some special cases with summer classes. Some summer semesters are concurrent (because of Summer_Full courses), so courses in concurrent semesters do not get disabled. 

Closes #906

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe how you tested this PR (both manually and with tests)
Provide instructions so we can reproduce. 

- [ ] Added integration tests

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where needed 
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-06 15:16 UTC, IrisLiu-00 commented on packages/server/test/login.integration.ts
> +        it('saves data for returning professor', async () => {
This is a test for that bug we fixed at the start of this summer, where returning profs weren't getting their data saved

2022-06-09 23:36 UTC, dfarooq610 requested changes
looks good, it would be nice to have one more assert to test the transition of summer 1 into summer 2

2022-06-09 23:36 UTC, dfarooq610 commented on packages/server/test/login.integration.ts
> +
can we add an assert to expect the summer1 class to be disabled when a summer 2 course is added?

2022-06-09 23:36 UTC, dfarooq610 commented on packages/server/src/login/login-course.service.ts
> +  // all courses from the previous semester.
mutation 😍

2022-06-13 00:51 UTC, dfarooq610 approved these changes
Nice!

2023-02-09 05:44 UTC, merged